#.travis.yml

language: node_js
node_js:
  - "7"

branches:
  only:
    - master

before_script:
  - npm install -g firebase
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
- ng lint --typeCheck
- ng test -sr
- ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change